baseurl = "https://example.com/"
title = "Site Title"
theme = "pulp"
canonifyurls = true
hasCJKLanguage = true
# pygmentsCodefences = true
# pygmentsUseClasses = true
# googleAnalytics = "{your tracking code}"

[markup.goldmark.renderer]
    unsafe = true # Allow user HTML tags

[params]
    author = "Your Name"
    avatar = "avatar.jpg"
    # avatarDescription = "My avatar description"
    favicon = "favicon.ico"
    description = """
        Please write anything here.
        Profiles, backgrounds, favorite things etc.
    """
    publicationYear = "2019"
    # listPageDateFormat = "January, 2006" # See https://gohugo.io/functions/format/
    # singlePageDateFormat = "January 2, 2006"
    # custom_css = ["/css/custom.css"]
    # custom_js = ["/js/custom.js"]

# Make sure setting a following option for search bar to work
[outputs]
    section = ["JSON", "HTML"]
    term = ["JSON", "HTML"]

[[menu.main]]
    identifier = "blog"
    # name = "Blog" #If display text link, cancel comment out
    pre = "<i class='fa fa-book-open fa-lg'></i>" #Choose your favorite font from Font Awesome
    url = "/blog/"
    weight = 10

[[menu.main]]
    identifier = "twitter"
    # name = "Twitter"
    pre = "<i class='fab fa-twitter fa-lg'></i>"
    url = "https://twitter.com/username"
    weight = 20

[[menu.main]]
    identifier = "github"
    # name = "GitHub"
    pre = "<i class='fab fa-github fa-lg'></i>"
    url = "https://github.com/username"
    weight = 30

[[menu.main]]
    identifier = "email"
    # name = "Email"
    pre = "<i class='fa fa-envelope fa-lg'></i>"
    url = "mailto:username@example.com"
    weight = 40
